services:
  n8n-frontend:
    image: ghcr.io/mgrsc/n8n_frontend:latest
    container_name: n8n-frontend
    ports:
      - "5173:80"
    volumes:
      # Mount configuration files (read-only for security)
      - ./agents.toml:/app/public/agents.toml:ro
      - ./public/favicon.svg:/app/public/favicon.svg:ro
    env_file:
      - ./.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge
